/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{html,js,svelte,ts}'],
  theme: {
    extend: {
      colors: {
        "obsidian-base": "#06090F",
        "error-container": "#93000a",
        "inverse-primary": "#9900cf",
        "electric-cyan": "#00F0FF",
        "obsidian-surface": "#121826",
        "on-background": "#dde2f4",
        "on-surface-variant": "#d4c0d7",
        "kinetic-purple": "#BD00FF",
        "outline-variant": "#514255",
        "on-error": "#690005",
        "on-tertiary-container": "#ffffff",
        "data-white": "#F1F5F9",
        "primary-fixed-dim": "#ecb2ff",
        "on-primary-fixed": "#320047",
        "on-primary": "#520071",
        "on-tertiary": "#00363a",
        "secondary-fixed": "#ffd9dc",
        "surface-container-high": "#242a37",
        "surface-container-lowest": "#080e1a",
        "secondary-container": "#ff4f73",
        "on-error-container": "#ffdad6",
        "background": "#0d131f",
        "on-secondary": "#670020",
        "inverse-on-surface": "#2b303e",
        "surface-variant": "#2f3542",
        "secondary-fixed-dim": "#ffb2ba",
        "surface-container-highest": "#2f3542",
        "on-secondary-container": "#5a001b",
        "on-surface": "#dde2f4",
        "primary-fixed": "#f8d8ff",
        "tertiary": "#00dbe9",
        "tertiary-fixed-dim": "#00dbe9",
        "secondary": "#ffb2ba",
        "primary": "#ecb2ff",
        "error": "#ffb4ab",
        "tertiary-fixed": "#7df4ff",
        "on-primary-container": "#ffffff",
        "primary-container": "#bd00ff",
        "surface-container-low": "#161c28",
        "on-tertiary-fixed": "#002022",
        "inverse-surface": "#dde2f4",
        "surface-bright": "#333947",
        "on-secondary-fixed": "#400011",
        "surface-dim": "#0d131f",
        "tertiary-container": "#00838b",
        "surface-tint": "#ecb2ff",
        "neon-magenta": "#FF005C",
        "outline": "#9d8ba0",
        "surface": "#0d131f",
        "on-tertiary-fixed-variant": "#004f54",
        "surface-container": "#1a202c",
        "on-secondary-fixed-variant": "#910031",
        "on-primary-fixed-variant": "#74009f"
      },
      spacing: {
        "unit": "4px",
        "margin-mobile": "16px",
        "space-md": "20px",
        "space-xs": "4px",
        "space-xl": "56px",
        "space-lg": "32px",
        "margin-desktop": "40px",
        "space-sm": "12px",
        "gutter": "16px"
      },
      fontFamily: {
        "headline-lg": ["Geist", "sans-serif"],
        "mono-data": ["JetBrains Mono", "monospace"],
        "title-md": ["Geist", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "mono-data": ["14px", { "lineHeight": "20px", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "title-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "600" }],
        "body-md": ["15px", { "lineHeight": "22px", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "52px", "letterSpacing": "-0.04em", "fontWeight": "800" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }]
      }
    }
  }
}
