"""Add User table

Revision ID: 3aa30e84c8f6
Revises: a1b2c3d4e5f6
Create Date: 2026-08-26 02:44:27.071804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3aa30e84c8f6'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipo_filings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('filing_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('s1_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipo_filings_id'), 'ipo_filings', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('ipo_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipo_filing_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('report_json', sa.JSON(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['ipo_filing_id'], ['ipo_filings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipo_reports_id'), 'ipo_reports', ['id'], unique=False)
    op.drop_constraint(op.f('uq_raw_item_ticker_url'), 'raw_items', type_='unique')
    op.alter_column('ticker_daily_sentiment', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('tickers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ticker_daily_sentiment', 'date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq_raw_item_ticker_url'), 'raw_items', ['ticker_id', 'source_url'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_ipo_reports_id'), table_name='ipo_reports')
    op.drop_table('ipo_reports')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ipo_filings_id'), table_name='ipo_filings')
    op.drop_table('ipo_filings')
    # ### end Alembic commands ###
